name: Sync Problems

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 23.6.1
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Generate Prisma client
      run: pnpm prisma generate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Sync problems with the database
      run: pnpm sync-problems
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
