name: Sync Problems

on:
  push:
    branches: ["main"]

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Sync problems with the database
      run: pnpm sync-problems
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
